version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "home-data-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j3zlksv5tvss"
s3_prefix = "home-data-api"
region = "eu-west-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
